export const booksWithIds = [
  { id: "GEN", name: "Genèse" },
  { id: "EXO", name: "Exode" },
  { id: "LEV", name: "Lévitique" },
  { id: "NUM", name: "Nombres" },
  { id: "DEU", name: "Deutéronome" },
  { id: "JOS", name: "Josué" },
  { id: "JDG", name: "Juges" },
  { id: "RUT", name: "Ruth" },
  { id: "1SA", name: "1 Samuel" },
  { id: "2SA", name: "2 Samuel" },
  { id: "1KI", name: "1 Rois" },
  { id: "2KI", name: "2 Rois" },
  { id: "1CH", name: "1 Chroniques" },
  { id: "2CH", name: "2 Chroniques" },
  { id: "EZR", name: "Esdras" },
  { id: "NEH", name: "Néhémie" },
  { id: "EST", name: "Esther" },
  { id: "JOB", name: "Job" },
  { id: "PSA", name: "Psaumes" },
  { id: "PRO", name: "Proverbes" },
  { id: "ECC", name: "Ecclésiaste" },
  { id: "SNG", name: "Cantique des Cantiques" },
  { id: "ISA", name: "Ésaïe" },
  { id: "JER", name: "Jérémie" },
  { id: "LAM", name: "Lamentations de Jérémie" },
  { id: "EZK", name: "Ézéchiel" },
  { id: "DAN", name: "Daniel" },
  { id: "HOS", name: "Osée" },
  { id: "JOL", name: "Joël" },
  { id: "AMO", name: "Amos" },
  { id: "OBA", name: "Abdias" },
  { id: "JON", name: "Jonas" },
  { id: "MIC", name: "Michée" },
  { id: "NAM", name: "Nahum" },
  { id: "HAB", name: "Habakuk" },
  { id: "ZEP", name: "Sophonie" },
  { id: "HAG", name: "Aggée" },
  { id: "ZEC", name: "Zacharie" },
  { id: "MAL", name: "Malachie" },
  { id: "MAT", name: "Matthieu" },
  { id: "MRK", name: "Marc" },
  { id: "LUK", name: "Luc" },
  { id: "JHN", name: "Jean" },
  { id: "ACT", name: "Actes" },
  { id: "ROM", name: "Romains" },
  { id: "1CO", name: "1 Corinthiens" },
  { id: "2CO", name: "2 Corinthiens" },
  { id: "GAL", name: "Galates" },
  { id: "EPH", name: "Éphésiens" },
  { id: "PHP", name: "Philippiens" },
  { id: "COL", name: "Colossiens" },
  { id: "1TH", name: "1 Thessaloniciens" },
  { id: "2TH", name: "2 Thessaloniciens" },
  { id: "1TI", name: "1 Timothée" },
  { id: "2TI", name: "2 Timothée" },
  { id: "TIT", name: "Tite" },
  { id: "PHM", name: "Philémon" },
  { id: "HEB", name: "Hébreux" },
  { id: "JAS", name: "Jacques" },
  { id: "1PE", name: "1 Pierre" },
  { id: "2PE", name: "2 Pierre" },
  { id: "1JN", name: "1 Jean" },
  { id: "2JN", name: "2 Jean" },
  { id: "3JN", name: "3 Jean" },
  { id: "JUD", name: "Jude" },
  { id: "REV", name: "Apocalypse" },
];



export const bookNames = [
  "Genèse", "Exode", "Lévitique", "Nombres", "Deutéronome", 
  "Josué", "Juges", "Ruth", "1 Samuel", "2 Samuel", 
  "1 Rois", "2 Rois", "1 Chroniques", "2 Chroniques", 
  "Esdras", "Néhémie", "Esther", "Job", "Psaumes", 
  "Proverbes", "Ecclésiaste", "Cantique des Cantiques", "Ésaïe", 
  "Jérémie", "Lamentations de Jérémie", "Ézéchiel", "Daniel", 
  "Osée", "Joël", "Amos", "Abdias", "Jonas", 
  "Michée", "Nahum", "Habakuk", "Sophonie", "Aggée", 
  "Zacharie", "Malachie", "Matthieu", "Marc", "Luc", 
  "Jean", "Actes", "Romains", "1 Corinthiens", "2 Corinthiens", 
  "Galates", "Éphésiens", "Philippiens", "Colossiens", "1 Thessaloniciens", 
  "2 Thessaloniciens", "1 Timothée", "2 Timothée", "Tite", "Philémon", 
  "Hébreux", "Jacques", "1 Pierre", "2 Pierre", "1 Jean", 
  "2 Jean", "3 Jean", "Jude", "Apocalypse"
];



export const bookIds = [
  "GEN", "EXO", "LEV", "NUM", "DEU", 
  "JOS", "JDG", "RUT", "1SA", "2SA", 
  "1KI", "2KI", "1CH", "2CH", "EZR", 
  "NEH", "EST", "JOB", "PSA", "PRO", 
  "ECC", "SNG", "ISA", "JER", "LAM", 
  "EZK", "DAN", "HOS", "JOL", "AMO", 
  "OBA", "JON", "MIC", "NAM", "HAB", 
  "ZEP", "HAG", "ZEC", "MAL", "MAT", 
  "MRK", "LUK", "JHN", "ACT", "ROM", 
  "1CO", "2CO", "GAL", "EPH", "PHP", 
  "COL", "1TH", "2TH", "1TI", "2TI", 
  "TIT", "PHM", "HEB", "JAS", "1PE", 
  "2PE", "1JN", "2JN", "3JN", "JUD", 
  "REV"
];
